### ISSUE TITLE
Minimum JDK version

### ISSUE THREAD

**Issue by mtruyens** [vlaaad/reveal#8]
I executed the "Give it a try" section, but immediately got an error: 

```
Syntax error (ClassNotFoundException) compiling at (cljfx/coerce.clj:1:1).
javafx.event.EventHandler

```

I suspect this is due to the fact that I use JDK8 (as so many still do...)? Perhaps useful to mention this in the documentation?

**Comment by vlaaad** [comment]
JDK 8 is supported, but there is a catch: JavaFX (a JVM UI framework). JavaFX was part of a JDK that was extracted to a separate project since Java 9. Hence, maven dependencies are configured in a way that expects JavaFX to be present in JDK on Java 8. Some distributions of Java 8 don't include JavaFX. You need either JDK 8 that includes JavaFX or more recent JDK.
